name: JeuDeLaVie
version: 1.0.0
main: ch.reaamz.jeudelavie.JeuDeLaVie
author: Reaamz
website: https://github.com/Loucool111/
commands:
   jdlv:
      description: Permet de contrôler le jeu
      usage: /jdlv (start | stop | reset | settime <duration>)